# Use a Python runtime as the base image 
FROM python:3.9.13-slim

# Set the working directory 
WORKDIR /waste_classification

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Copy the main.py file into the container as well
COPY main.py .

# Copy the model weights into the container
COPY ft_model.pt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install uvicorn python-multipart

# Run the api when the container launches
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]